"""empty message

Revision ID: 00fb6681a097
Revises: cc6506b63b4d
Create Date: 2022-02-04 15:53:54.465146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fb6681a097'
down_revision = 'cc6506b63b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('opportunity', 'position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity', sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('opportunity', 'title')
    # ### end Alembic commands ###
