"""empty message

Revision ID: 74e5f3b0d3c6
Revises: f8d2ff843d1d
Create Date: 2022-02-07 21:56:22.556029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e5f3b0d3c6'
down_revision = 'f8d2ff843d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('year', sa.String(), nullable=True))
    op.drop_column('publication', 'published_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('published_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('publication', 'year')
    # ### end Alembic commands ###
