"""empty message

Revision ID: 8520f7cdaeaf
Revises: 94dd60b41468
Create Date: 2022-02-04 10:24:34.643809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8520f7cdaeaf'
down_revision = '94dd60b41468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'link')
    # ### end Alembic commands ###
