"""empty message

Revision ID: 94dd60b41468
Revises: 20ca81914542
Create Date: 2022-02-04 09:55:25.693150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94dd60b41468'
down_revision = '20ca81914542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('title', sa.String(), nullable=False))
    op.add_column('publication', sa.Column('published_at', sa.Date(), nullable=False))
    op.add_column('publication', sa.Column('publisher', sa.String(), nullable=False))
    op.add_column('publication', sa.Column('author', sa.String(), nullable=False))
    op.add_column('publication', sa.Column('is_cover', sa.Boolean(), nullable=True))
    op.drop_column('publication', 'posted_at')
    op.drop_column('publication', 'position')
    op.drop_column('publication', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('publication', sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('publication', sa.Column('posted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('publication', 'is_cover')
    op.drop_column('publication', 'author')
    op.drop_column('publication', 'publisher')
    op.drop_column('publication', 'published_at')
    op.drop_column('publication', 'title')
    # ### end Alembic commands ###
