"""empty message

Revision ID: b654f16f8071
Revises: 00fb6681a097
Create Date: 2022-02-07 17:12:06.616472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b654f16f8071'
down_revision = '00fb6681a097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publication', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('publication', 'published_at',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('publication', 'publisher',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('publication', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publication', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('publication', 'publisher',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('publication', 'published_at',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('publication', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
