"""empty message

Revision ID: db74bd3cd4f3
Revises: b654f16f8071
Create Date: 2022-02-07 17:24:03.833192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db74bd3cd4f3'
down_revision = 'b654f16f8071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'published_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('published_at', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
